How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Globals.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\IFTTT.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\International.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Program.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\variables.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\3rdParty\ADL.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\3rdParty\NVAPI.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\3rdParty\PInvokeDelegateFactory.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Algorithms\Algorithm.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Algorithms\DualAlgorithm.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Benchmarking\BenchmarkHandler.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Benchmarking\BenchHelpers\ClaymoreZcashBenchHelper.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Benchmarking\BenchHelpers\CpuBenchHelper.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Benchmarking\BenchHelpers\PowerHelper.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\ConfigManager.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\ConfigJsonFile\ConfigFile.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\ConfigJsonFile\DeviceBenchmarkConfigFile.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\ConfigJsonFile\FOLDERS.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\ConfigJsonFile\GeneralConfigFile.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\Data\AlgorithmConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\Data\BenchmarkTimeLimitsConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\Data\ComputeDeviceConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\Data\DeviceBenchmarkConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\Data\DeviceDetectionConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\Data\DualAlgorithmConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Configs\Data\GeneralConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\AmdGpuDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDeviceManager.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\CPUUtils.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\CudaDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\CUDA_Unsupported.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\GroupNames.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\OpenCLDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\Algorithms\DefaultAlgorithms.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\Algorithms\GroupAlgorithms.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDevice\AmdComputeDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDevice\ComputeDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDevice\CPUComputeDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDevice\CPUReader.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\ComputeDevice\CudaComputeDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\Querying\AmdQuery.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\Querying\OpenCLJsonData.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Devices\Querying\VideoControllerData.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\DriverVersionConfirmationDialog.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\DriverVersionConfirmationDialog.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_3rdParty_TOS.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_3rdParty_TOS.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Benchmark.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Benchmark.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_ChooseLanguage.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_ChooseLanguage.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_DcriValues.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_DcriValues.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Loading.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Loading.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Main.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Settings.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Form_Settings.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\MinerFileNotFoundDialog.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\MinerFileNotFoundDialog.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\TextBoxKeyPressEvents.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\AlgorithmSettingsControl.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\AlgorithmsListView.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\AlgorithmsListView.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\BenchmarkLimitControl.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\BenchmarkLimitControl.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\BenchmarkOptions.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\BenchmarkOptions.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\DevicesListViewEnableControl.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\Field.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\Field.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\GroupProfitControl.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Forms\Components\GroupProfitControl.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Interfaces\IBenchmarkCalculation.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Interfaces\IBenchmarkComunicator.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Interfaces\IBenchmarkForm.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Interfaces\IListItemCheckColorSetter.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Interfaces\IMainFormRatesComunication.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Interfaces\IMessageNotifier.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Interfaces\IMinerUpdateIndicator.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Bminer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\castxmr.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ccminer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ClaymoreBaseMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ClaymoreCryptoNightMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ClaymoreDual.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ClaymoreNeoscryptMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\cpuminer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\CryptoDredge.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Ethlargement.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\EWBF.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\GMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\hsrneoscrypt.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\lolMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\lolMinerBEAM.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\lyclMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Miner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\MinerFactory.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\MinersApiPortsManager.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\MinersManager.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\MinersSettingsManager.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\MiningSession.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\miniZ.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\mkxminer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\NBMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Phoenix.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\prospector.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\sgminer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\SRBMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\teamredminer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\trex.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\TTMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\WildRig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Xmrig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\XmrigAMD.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\XmrigNVIDIA.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Z-Enemy.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Equihash\ClaymoreZcashMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Equihash\Dstm.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Equihash\NhEqBase.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Equihash\NhEqMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Equihash\OptiminerZcashMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ethminer\Ethereum.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ethminer\MinerEtherum.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ethminer\MinerEtherumCUDA.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\ethminer\MinerEtherumOCL.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\GroupingLogic.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\GroupMiner.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\GroupSetupUtils.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\MinerPaths.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\MiningDevice.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\MiningPair.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Grouping\MiningSetup.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Obsolete\eqm.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Obsolete\Excavator.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Parsing\ExtraLaunchParameters.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Parsing\ExtraLaunchParametersParser.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Parsing\MinerOption.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\Parsing\MinerOptionPackage.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\XmrStak\XmrStak.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\XmrStak\Configs\XmrStakConfig.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\XmrStak\Configs\XmrStakConfigCpu.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\XmrStak\Configs\XmrStakConfigGpu.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Miners\XmrStak\Configs\XmrStakConfigPool.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\obj\Debug\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\obj\Debug\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\obj\Debug\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\obj\Release\TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\obj\Release\TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\obj\Release\TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\PInvoke\CPUID.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\PInvoke\NiceHashProcess.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\PInvoke\PInvokeHelpers.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Properties\AssemblyInfo.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Properties\Resources.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Properties\Settings.Designer.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Stats\ExchangeRateAPI.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Stats\NiceHashSocket.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Stats\NiceHashStats.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Switching\AlgorithmHistory.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Switching\AlgorithmSwitchingManager.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Switching\Interval.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Switching\Models.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Switching\NHSmaData.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\AlgorithmNiceHashNames.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\BINS_CODEGEN.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\BINS_CODEGEN_3rd.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\BitcoinAddress.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\CommandLineParser.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\DownloadSetup.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\Extensions.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\Helpers.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\Links.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\Logger.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\MemoryHelper.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\MinersDownloader.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\MinersDownloadManager.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\MinersExistanceChecker.cs
How-To-Use-PVS-Studio-FREE.exe --comment 2 -m D:\NiceHashMinerLegacy\NiceHashMinerLegacy\NiceHashMiner\Utils\ProfitabilityCalculator.cs
