namespace NiceHashMinerLegacy.Common.Enums
{
    public enum MinerType
    {
        NONE,
        ccminer,
        ccminer_CryptoNight,
        ethminer_OCL,
        ethminer_CUDA,
        sgminer,
        cpuminer_opt,
        nheqminer_CPU,
        nheqminer_CUDA,
        nheqminer_AMD,
        eqm_CPU,
        eqm_CUDA,
        ClaymoreZcash,
        ClaymoreCryptoNight,
        OptiminerZcash,
        excavator,
        ClaymoreDual,
        EWBF,
        Xmrig,
        XmrigAMD,
        dstm,
        CastXMR,
        hsrneoscrypt,
        ClaymoreNeoscrypt,
        CryptoDredge,
        ZEnemy,
        lyclMiner,
        trex,
        mkxminer,
        Phoenix,
        END
    }
}
